version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.99.0/24
    

services:  
  # nginx
  web-misur:
    build: misur
    container_name: misur
    restart: always
    working_dir: /var/www/misur
    volumes:
      - ../php/src/misur:/var/www/misur
    networks:
      default:
        aliases:
          - mis_network

  web-misur-laravel:
    build: misur
    container_name: misur-laravel
    restart: always
    working_dir: /var/www/misur-laravel
    volumes:
      - ../php/src/misur-laravel:/var/www/misur-laravel
    networks:
      default:
        aliases:
          - mis_network

  web-cmbiz:
    build: cmbiz
    container_name: cmbiz
    restart: always
    working_dir: /var/www/cmbiz
    volumes:
      - ../php/src/cmbiz:/var/www/cmbiz
    networks:
      default:
        aliases:
          - mis_network

  web-rems:
    build: rems
    container_name: rems
    restart: always
    working_dir: /var/www/rems
    volumes:
      - ../php/src/rems:/var/www/rems
    networks:
      default:
        aliases:
          - mis_network
  
  web-csc:
    build: csc
    container_name: csc
    restart: always
    working_dir: /var/www/csc
    volumes:
      - ../php/src/csc:/var/www/csc
    networks:
      default:
        aliases:
          - mis_network

  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "8080:80"
      - "8081:81"
      - "8082:82"
      - "8083:83"
      - "8084:84"
    volumes:
      #- ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-config:/etc/nginx/conf.d
      - ../php/src/misur:/var/www/misur
      - ../php/src/cmbiz:/var/www/cmbiz
      - ../php/src/rems:/var/www/rems
      - ../php/src/csc:/var/www/csc
      - ../php/src/misur-laravel:/var/www/misur-laravel
    networks:
      default:
        aliases:
          - mis_network
  
  